# Shared static system configuration

config_version = 1

[general]
# The default pipeline to use when running the brokkr status and brokkr monitor commands
monitoring_pipeline_default = "monitor"
# The value to use to designate NA values when data is serialized
na_marker = "NA"
# How to format the output filename on the client.
# Items in {} are replaced with their corresponding value
output_filename_client = "{output_type}_{system_prefix}_{unit_number:0>4}_{utc_date!s}.{extension}"
# The path the client should use when storing output data files
output_path_client = "~/brokkr/{system_name}"
# How long to wait for the workers to shut down after sending the command
worker_shutdown_wait_s = 10

# Include this section if using the built-in AutoSSH functionality for remote access and data upload.
# It can be ignored if you are using a different network uplink method not requiring SSH.
#[autossh]
# Hostname of the server to connect to
#server_hostname = "proxy.nsstc.uah.edu"
# Username to use on the server
#server_username = ""
# Base offset to the tunnel port to expose on the server (port = offset + unit_number)
#tunnel_port_offset = 9000

# List custom steps or override default preset settings here under the [steps] key
[steps.monitor_csv_output]
# Preset for this step, in the format "{device_name}.{input/output/command/etc}.{preset_name}"
_preset = "builtins.outputs.csv_file"
# Step name, for use in UI text and log messages
name = "Monitoring CSV Output"
# Step-specific settings; here lists the output path and filename kwargs
output_path = "monitoring"
filename_kwargs = { output_type = "monitoring" }

[steps.dht11_input]
_preset = "adafruit_dht.inputs.dht11"
pin = 17

[steps.dht22_input]
_preset = "adafruit_dht.inputs.dht22"
pin = 27

[steps.ec5_input]
_preset = "meter_ech2o.inputs.ec5_ads1115"
adc_channel = 2

# List pipelines to run here under the [pipelines] key
[pipelines.monitor]
# Custom builder for this pipeline, e.g. a streamlined builder for monitoring pipelines
_builder = "monitor"
# Name of this pipeline for UI text and log messages
name = "Monitoring"
# Custom settings for this pipeline type: here, the interval in s to run monitoring
monitor_interval_s = 10
# Most pipeline builders will need one or more lists of steps.
# These are either names of steps in the [steps] table, or preset names as above
monitor_input_steps = [
    "builtins.inputs.current_time",
    "builtins.inputs.run_time",
    "adafruit_htu21d.inputs.htu21d",
    "dht11_input",
    "dht22_input",
    "ec5_input",
    "adafruit_sht31.inputs.sht31d",
    "adafruit_bmp280.inputs.bmp280_i2c",
]
monitor_output_steps = [ "monitor_csv_output" ]
